[package]
org = "luheerathan"
name = "remote_central_mock"
version = "0.1.0"
distribution = "2201.8.8"

[build-options]
observabilityIncluded = true

# [[dependency]]
# org="ballerina"
# name="cloud"
# version="3.1.0"
